name: ETL Deployment
on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: update system
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y python3-pip

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::716563790644:role/git-ops
          aws-region: us-west-1
          

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0  

  
      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  
      - name: Run TFLint
        id: lint
        run: tflint -f compact

      - name: terraform configure
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        id: apply
        run: |
          terraform init
          terraform validate
          terraform apply --auto-approve 
        working-directory: ./aws

      - name: logs
        if: failure()
        run: |
          echo "Terraform apply failed. Please check the logs for details."
          echo "Fetching logs..."
          terraform show -json > terraform_logs.json
          cat terraform_logs.json

      - name: Notify on success
        if: steps.apply.outcome == 'success'
        run: |
          echo "Terraform apply succeeded. Deployment completed successfully."